### ISSUE TITLE
front-end-knowledge-base (libraries)

### ISSUE THREAD

**Issue by p-shapov** [fullstack-development/front-end-knowledge-base#1]
https://github.com/fullstack-development/front-end-knowledge-base/blob/0fe3fe19069c786beb08bf7f9f4c2aa0b29e04bc/React/libraries/README.md?plain=1#L17

Предлагаю рассмотреть следующие либы)

### [@headlessui/react](https://headlessui.com/)
Набор базовых ui-компонентов. Легко кастомится за счет композабельности, минималистичного API и отстутсвия лишней стилизации. Так же из коробки имеет все плюшки для a11y. Есть своя реализация транзишна перед дестроем компонента ([Transition-компонент](https://headlessui.com/react/transition)).

### [ariakit](https://ariakit.org/)
Очень похож на @headlessui/react. Как и @headlessui/react, все компоненты реализованы в соответсвии со рекомендацияи WAI-ARIA, но отличие в том, что либа имеет больший набор базовых компонентов и предоставляет набор хуков для более гибкого взаимодействия со стейтом виджетов извне. Так же имеет в запасе низкоуровневые компоненты для создания своих доступных компонентов. Из плюсов - очень гибкое апи, нет лишней стилизации, легко кастомизируется за счет композабельности, a11y. Минусы - неустоявшаяся спека и неполная документация (находится на стадии альфы).

### [@rehokify/datepicker](https://github.com/rehookify/datepicker)
Набор декларативных хуков для создания дейтпикеров для тех, кому надоело переопределять дефолтные стили и разметку у компонентов, предоставляемых ui-kit'ми. Из минусов - либа относительно молодая, маленькое комьюнити. Из-за этого может быть много неотловленных эдж-кейсов

### [remirror](https://remirror.io/)
Либа для контруирования wysiwyg редакторов любой разновидности и сложности. Имеет очень гибкое апи с возможностью добавления экстеншнов (есть как builtin-решения, так и возможность сделать свой кастомный вариант)

**Comment by FanManutd** [comment]
> @headlessui/react

Сталкивался с этой либой на одном из проектов. Претензий нет, кроме скудного набора компонентов. Я добавлю это в минусы, если не против. Не хотелось бы тащить на проект 2 или более ui-библиотек. 

> ariakit

Глянул доку, выглядит очень даже интересно. Мне понравилась идея со стейт-хуками. А ты уже использовал эту либу где-то или просто следишь за ней? Мне кажется тащить на проект либу в альфе, с неустаявшимся API и действительно неполной документацией (что оч важно) - не самая лучшая затея. Хотя повторюсь, меня заинтересовало. Я предлагаю продолжить наблюдать за ней и добавить её сюда после того, как она выйдет из альфы.

По остальному вопросов нет)

**Comment by p-shapov** [comment]
> А ты уже использовал эту либу где-то или просто следишь за ней?

Я использовал ее на пет проекте, по ходу работы каких то особых нареканий не увидел) Просто на момент, когда писал ишью, решил глянуть доку и обнаружил, что она довольно таки скудная. Ну и про то, что она до сих пор в стадии альфы, приметил в тот же момент. Но все равно, либа прям очень классная. Особенно, если заказчик требует доступность (там даже навигация с клавиатуры реализована по табам). Собственно поэтому и решил о ней как минимум рассказать)

> Претензий нет, кроме скудного набора компонентов. 

Да, определенно в минусы стоит записать. Но для создания базовых компонентов, вроде модалок, селектов, попапов, табов и тд как по мне это идеальный вариант. Все таки минималистичность либы в этом моменте перевешивает для меня скудность функционала)
